viamrobotics/board_canaries

- install.sh
- requirements.txt
- test_gpios.py
I should have done this originally! but didn't think it through enough.
Hopefully, if you ignore whitespace changes (everything got indented 1 level), and maybe go commit-by-commit, this is straightforward.
~~TODO: don't merge this until the installer script from https://github.com/viamrobotics/board_canaries/pull/2 is changed to `pip install -r requirements.txt`.~~ edit: done!
> Move the canary tests to a testing framework

- install.sh
Apparently `uname -i` is not guaranteed to work on all platforms, while `uname -m` is. For every board I've tried except the Beaglebone (Orin, Orin Nano, Odroid, rpi, and my Framework laptop), they provide identical output. On the Beaglebone, `-i` gives back "unknown" while `-m` gives back useful data.
> [RSDK-4766] Fix canary installer

- canary_config.example.py
- test_gpios.py
Problem: the Beaglebone AI-64 pins seem to be either GPIO or PWM, but not both. The canary tests want to test both.
Solution: if you only define one set of pins in the test config, use those for everything. If you define a second set, though, do different tests on the different pins.
Tried on an Orin Nano with only 1 set of pins defined: the tests all pass.
Tried on a Beaglebone AI-64 with 2 sets of pins defined: the tests all pass again!
> [RSDK-4766] give the option of specifying other pins for PWM/interrupts

- test_gpios.py
Hopefully the comment in the code explains it. Tried on a Jetson Orin: test still passes, but the old version passed most of the time, too.
> wait a short while after turning on PWM before starting to count the cycles

- canary_tests.sh
- requirements.txt
- test_gpios.py
The comment in the code should explain it.
Tried on an Orin: the test passes, but the old version usually passes, too.
> retry the connection several times

- test_gpios.py
Adds test for software PWM on the board canaries. I tested this on the UP using pins 27 and 28 and it passed. Once approved I will edit the configs for the other canary boards and test.
> RSDK-3952 Software PWM test

- test_gpios.py
A bunch of tiny changes:
- Bump the allowable error up to 10%. The worst error we've seen so far is 9%. I don't like how big it is, but until we redo this to work more accurately, I don't think there's much we can do about it. :disappointed: 
- Reduce the PWM frequency from 50 Hertz to 40. By making it slower, hopefully the computer can keep up with the changes better. (Thanks to Rand for the idea!)
- Remove the trailing whitespace that was added to a couple lines. IIRC you use VSCode: here's [how to do that automatically](https://stackoverflow.com/questions/30884131/remove-trailing-spaces-automatically-or-with-a-shortcut) when you save a file.
- Rename the test to be about interrupts _and PWM._
- Make the `parameterized.expand` arguments tuples. This should hopefully make them easier to …
> make the software PWM test much more forgiving

- canary_tests.sh
This will help with https://viam.atlassian.net/browse/RSDK-6252 if it happens again.
Not tested: given that we can't reliably reproduce the issue, I don't even know how I'd go about testing it. but my expectation is that this is right, and then we'll get more details next time the panic happens.
> turn on Rust backtracing, in case we hit that panic again

- analyze_logs.py
- check_slack_connectivity.py
- slack_reporter.py
- test_gpios.py
The changes are:
- Reporting stuff to Slack has been refactored into a new file, `slack_reporter.py`
- If the canary board tests are unable to connect to the RDK, report that to Slack and then try a second time before failing the test.
I suspect the easiest way to review this is commit-by-commit, though there were a few mistakes I made in early commits that I fixed in later ones without reworking the history.
I haven't tried this out yet, but intend to put it through its paces in the un-archived #temp_to_remove channel...
> Retry connection if it fails

- analyze_logs.sh
- crontab_template.txt
Because this changes the crontab template, we need to manually install this on all the boards. This kind of thing is what [Salt](https://docs.saltproject.io/en/master/topics/tutorials/walkthrough.html#salt-in-10-minutes/) is intended to do. but we have so few boards that it's not worth the hassle to set that up yet.
So, we shouldn't check this in until we're willing to manually update the crontabs on all the board canaries (likely by re-running `install.sh` on each of them). 
For the moment, I'm not adding in anything about log rotation. We add a couple kilobytes to the logs every night, which means we'll add less than a megabyte per year. If we rotate the logs once per decade, that's more than enough. :wink:
> Log to /var/log instead of /tmp

- slack_reporter.py
I noticed this while showing Gautham this file.
There won't be any behavioral changes here: the only place `report_file()` is used, the `filename` passed in is `"canary_tests.log"`. but now it's more correct so we can't hit this bug in the future.
> library functions should use their arguments

- requirements.txt
- test_gpios.py
Usually the canary tests pass fine, but sometimes the tick count for the HW PWM stuff is way too low. This PR prints out data about every interrupt we encounter, in the hopes that we can figure out what's going wrong.
Tried on an Orin Nano: works fine. We get lots of ticks printed out, and then the test passes. The cron job will pull the latest code from github, and then run `pip install -r requirements` to upgrade the SDK, so the boards should be able to upgrade themselves.
> Diagnose problems with counting ticks

- analyze_logs.py
This is a follow-up to https://github.com/viamrobotics/board_canaries/pull/24, which added new output from the tests to try to better diagnose the flakiness around PWM output. What I forgot was that the later analysis checks that the test output looks right and sends it to Slack if it doesn't. When the test output changed, we started sending it all to Slack! This PR corrects it, so the analysis ignores the new output.
Tried on the Orin AGX: without this change it (erroneously) reports to Slack that last night's test failed, and with the change, it (correctly) says the tests passed.
> ignore the new extra output when checking if the tests have passed

- analyze_logs.py
- stack_printing.py
- test_gpios.py
Twice recently, the tests have hung, and it would be nice to figure out _where_ they hung. With this PR, you can send a SIGUSR1 (e.g., `pkill -10 -f test_gpios`) and it'll print out stack traces of all threads and all active coroutines.
I don't have a great sense of how useful this will be: I can get output like the following.
```
Thread asyncio_0:
File /usr/lib/python3.11/threading.py, line 1002, in @_bootstrap
self._bootstrap_inner()
File /usr/lib/python3.11/threading.py, line 1045, in @_bootstrap_inner
self.run()
File /usr/lib/python3.11/threading.py, line 982, in @run
self._target(*self._args, **self._kwargs)
File /usr/lib/python3.11/concurrent/futures/thread.py, line 83, in @_worker
work_item.run()
File /usr/lib/python3.11/concurrent/futures/thread.py, line 58, in @run
result = …
```
> Print stacks on SIGUSR1

- test_gpios.py
Unless this causes a test failure, we don't really care about it on Slack. If it causes a test failure, it'll be written to the logs and we can see it there.
I haven't tried this out, but I'm pretty confident it's right.
> don't write to slack on connection failure

- stack_printing.py
Eventually, we'll be able to track down why the Python SDK is hanging sometimes. but it wasn't last night. Maybe next time.
Thanks to @dgottlieb for the advice!
> flush stdout after printing stack traces

- analyze_logs.sh
This is split out of https://github.com/viamrobotics/board_canaries/pull/30, to get a head start. The idea is that if we log the current date when analyzing the logs, the monitor can check whether the canaries have analyzed their tests each day and write to Slack if something has gone wrong. but to prevent it from writing to Slack on the very first day, we should start logging the date before then.
> logs analysis should include today's date, to make metaanalysis easier

- monitor_crontab.txt
Not described in this repo is the fact that the pi5 canary refuses to install any Python packages outside of a virtual environment. So, on the pi5 I installed everything inside one, and then edited the repo on that board to source the venv before running the Python scripts. Specifically, I added the line `source venv/bin/activate` inside both `analyze_logs.sh` and `canary_tests.sh`. That all worked fine. 
When the pi5 became the canary monitor, I also added that line inside the new cron entry, but didn't notice that cron was using `sh` instead of `bash` as its shell! and `sh` does not define `source`, so sourcing the venv was failing as an unknown command. The two files mentioned previously both start with `#!/bin/bash`, which is why they worked but the cron job didn't!
Thanks to …
> [RSDK-8108] the monitor crontab should use bash, not sh

- canary_tests.py
Tried on the Orin Nano: all tests pass.
> add sleep to GPIO tests, with todo to remove it again

- canary_tests.py
...in the hopes that we have fewer reconnection problems.
Tried on the Up4000 (the one that makes sure the monitor is online): all tests pass.
> Increase connection timeout

- canary_tests.sh
Tried on the Orin Nano: without this change, running `canary_tests.sh` failed because the pins were in use by a motor component on the normal RDK config. With this change, running it passed!
> stop the RDK server after updating (which likely started it up)

- analyze_logs.sh
- canary_tests.sh
- check_slack_connectivity.py
- install.sh
- monitor_crontab.txt
We've now had 2 boards that cannot install python stuff without a virtual environment, so let's switch the board canaries to doing everything in one, and then we won't have this problem again.
Before merging this, we need virtual environments on every pre-existing board. No need to install stuff within it; that would happen all over again when canary_tests.sh runs overnight.
> [RSDK-8519] Do everything from a virtual environment

- canary_tests.py
This corresponds to https://github.com/viamrobotics/rdk/pull/4297. Now that we don't expect any boards to have weird delays when turning on their pins, the tests should not allow for weird delays.
> [RDSK-8581] don't allow delays when enabling PWM signals

- install.sh
Otherwise, the daemon won't notice the new file exists, and won't run the tests! I wonder if there are other boards that are mistakenly not running tests because the crontab didn't get picked up. :eyes: 
Solution taken from https://stackoverflow.com/questions/10193788/restarting-cron-after-changing-crontab-file#10193931
> reload cron daemon after installing crontab

- README.md
- canary_config.example.py
- canary_tests.py
Updating boards to connect to the robot with API key since location secret is deprecated. I manually updated all the board's configs except for the orin which is not online and will need to be updated later.
> Update all boards to authenticate with API key instead of location secret 
